### ISSUE TITLE
Tidy Up for OPLのTask1の時間制限について

### ISSUE THREAD

**Issue by yuma116** [RoboCupAtHomeJP/Rule2021#1]
大元のTidy Upのルールでは，Task1の時間制限が15分となっており，RCAPルールでも上書きしていないので，現状このルールがそのまま採用されることになっています．
このルールですが，運営委員内で議論したところ，「オブジェクトが少ないため15分では長い，10分でも良いのではないか」との意見がありました．初期ルール設計者の意図としては，1オブジェクト3分弱で5個とも運べる時間計算としたつもりですが，参加チームのみなさまはどちらのルールが嬉しいでしょうか．
ご意見お待ちしております．

---

In the original Tidy Up rules, the time limit for Task 1 is 15 minutes, and since this has not been overridden by the RCAP rules, this rule is currently being adopted as is.
This rule was discussed among the committee members, and it was suggested that 15 minutes is too long because of the small number of objects, and that 10 minutes might be acceptable. The initial rule designer's intention was to calculate the time to carry all 5 objects in less than 3 minutes per object, but which rule would make the participating teams happier?
We are looking forward to your opinions.

**Comment by Ryo-sakamoto** [comment]
チームによっては,時間を掛けてでも確実に点数を取る戦略を取る場合に,10分では短いかと思うので,初期ルール設定の15分の方が良いのではないかと思います.

**Comment by Uma919** [comment]
ご連絡遅くなりまして申し訳ございません。
人員が不足していることもあり、時間が限られておりますので10分で検討いただけますと幸いです。

**Comment by yuma116** [comment]
@Uma919 
すみません，人員不足と10分ルールの関係がいまいち分からないのですが，どのような観点から10分の方が好ましいのでしょうか．
I'm sorry, but I don't quite understand the relationship between understaffing and the 10-minute rule. From what perspective is the 10-minute rule preferable?

**Comment by Uma919** [comment]
@yuma116 
お手数おかけします。
10分ルール適用により個々人の拘束時間が短縮されることになりますので、チーム内の限られた人員での配置転換がスムーズになると考えた次第です。

**Comment by yuma116** [comment]
@Uma919 
解釈が間違っていれば，申し訳ございません．競技時間が短くなれば，それだけ準備に時間を用意出来る，といったことをおっしゃっているのでしょうか．
競技会では競技が優先であり，かつ5分と短い時間のことですので，その点を気にする必要はないのでは考えますが，いかがでしょうか．

**Comment by Uma919** [comment]
@yuma116 
おっしゃる通りそういった指摘もあろうかと存じますが、手の空いた人員を他のリーグの補助に回すといったことになります。また、今回は3団体参加されておりますので合計15分に相当いたしますが、あくまで要望としてご一考いただければ幸いです。どうぞよろしくお願いいたします。

**Comment by yuma116** [comment]
@Uma919 
意図を把握いたしました．申し訳ございませんがそれはチームの事情であると考えますので，その意見は却下させて頂きます．
私は[しばらく前に坂本さんが書かれた意見](https://github.com/RoboCupAtHomeJP/Rule2021/issues/1#issuecomment-964064356)に同意しますので，特に問題がなければ15分でFIXしたいと考えておりますが，いかがでしょうか．

**Comment by Uma919** [comment]
@yuma116 
ご連絡遅くなりまして申し訳ございません。
かしこまりました。競技時間15分に同意いたします。

**Comment by yuma116** [comment]
では，本ルールは競技時間15分でFIXしたいと思います．
よろしくお願いいたします．
