### ISSUE TITLE
Robot Inspectionの開催について

### ISSUE THREAD

**Issue by Yuki-Ikeda0810** [RoboCupAtHomeJP/Rule2021#2]
[Tidy Up for OPLのルール](https://github.com/RoboCupAtHomeJP/Rule2021/blob/master/rules/tidyup_opl_ja.md)には、「ロボットインスペクションを通過したロボットが出場可能である」との記載があるのですが、本大会でもRobot Inspectionは行うのでしょうか？

Robot Inspectionを行う場合、開催する日時はいつになりますでしょうか？

また、ルールは[RoboCup2020](https://github.com/RoboCupAtHomeJP/Rule2020/blob/master/rules/robotinspection_ja.md)と同じ認識でよろしいでしょうか？

**Comment by yuma116** [comment]
**Robot Inspectionですが，例年通り「点数の入るタスク」として実施予定**です．[先ほどルールを公開いたしました．](https://github.com/RoboCupAtHomeJP/Rule2021/tree/3283d0c9c7c9da54c7d58f657aa3029b877a5b88) ルールはご指摘のとおりRooCup2020と同様です．ご確認お願いいたします．

私の伝達・公開ミスでルールの実施が分からない状態となっており，大変申し訳ございません．
