### ISSUE TITLE
競技開催の日程について

### ISSUE THREAD

**Issue by Yuki-Ikeda0810** [RoboCupAtHomeJP/Rule2021#3]
本大会では、Basic Functionalities、Tidy Up for OPL、Finalの3タスクを実施するとのことですが、これら競技スケジュールはどのようなものになっているのでしょうか？

何日にどのタスクを行うのかだけでも教えて頂けると幸いです。

**Comment by yuma116** [comment]
大変お待たせいたしました．競技スケジュールをこちらに公開いたしました．ご確認お願いいたします．
https://github.com/RoboCupAtHomeJP/AtHome2021/blob/master/Data/schedule.pdf
